-- =====================================================================
-- Sistema Web de Gestión Inmobiliaria — TFI TUP
-- Migración V1: esquema inicial (MVP)
-- Motor: PostgreSQL 15+
-- Formato compatible con Flyway (V<n>__descripcion.sql)
--
-- Convenciones:
--   * Tablas y columnas en snake_case, singular.
--   * PK: BIGINT GENERATED BY DEFAULT AS IDENTITY (compatible con
--     @GeneratedValue(strategy = GenerationType.IDENTITY) en JPA).
--   * Enums como VARCHAR + CHECK (se mapean con @Enumerated(EnumType.STRING)).
--     Se evita el tipo ENUM nativo de Postgres porque agregar/quitar valores
--     requiere ALTER TYPE y complica el mapeo con Hibernate.
--   * Fechas con TIMESTAMPTZ (se guardan en UTC, se muestran en hora local).
--   * No hay borrado físico: toda baja es lógica (activo / activa /
--     estado ELIMINADA). Por eso las FK usan ON DELETE RESTRICT.
-- =====================================================================


-- ---------------------------------------------------------------------
-- USUARIO: administradores del panel
-- ---------------------------------------------------------------------
CREATE TABLE usuario (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre          VARCHAR(80)  NOT NULL,
    apellido        VARCHAR(80)  NOT NULL,
    telefono        VARCHAR(30),
    email           VARCHAR(120) NOT NULL,
    clave_hash      VARCHAR(100) NOT NULL,          -- BCrypt (60 caracteres)
    rol             VARCHAR(20)  NOT NULL DEFAULT 'ADMIN',
    activo          BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_creacion  TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT ck_usuario_rol   CHECK (rol IN ('ADMIN')),
    CONSTRAINT ck_usuario_email CHECK (email LIKE '%_@_%')
);

-- Email único sin distinguir mayúsculas (Juan@x.com = juan@x.com)
CREATE UNIQUE INDEX ux_usuario_email ON usuario (lower(email));


-- ---------------------------------------------------------------------
-- PROPIEDAD: el inmueble físico (independiente de cómo se ofrece)
-- ---------------------------------------------------------------------
CREATE TABLE propiedad (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_propiedad          VARCHAR(20)   NOT NULL,
    resumen                 VARCHAR(500)  NOT NULL,
    direccion               VARCHAR(200)  NOT NULL,
    localidad               VARCHAR(100)  NOT NULL,
    cant_ambientes          SMALLINT      NOT NULL,
    cant_dormitorios        SMALLINT      NOT NULL,
    cant_banios             SMALLINT      NOT NULL,
    tiene_patio             BOOLEAN       NOT NULL DEFAULT FALSE,
    superficie_total        NUMERIC(10,2) NOT NULL,     -- m²
    anio_construccion       SMALLINT,                   -- NULL = desconocido
    activa                  BOOLEAN       NOT NULL DEFAULT TRUE,  -- baja lógica
    fecha_creacion          TIMESTAMPTZ   NOT NULL DEFAULT now(),
    fecha_ult_actualizacion TIMESTAMPTZ   NOT NULL DEFAULT now(),

    CONSTRAINT ck_propiedad_tipo
        CHECK (tipo_propiedad IN ('CASA', 'DEPARTAMENTO', 'PH', 'DUPLEX')),
    CONSTRAINT ck_propiedad_ambientes   CHECK (cant_ambientes >= 1),
    CONSTRAINT ck_propiedad_dormitorios CHECK (cant_dormitorios >= 0),
    -- Criterio argentino: los dormitorios cuentan como ambientes, y siempre
    -- hay al menos un ambiente que no es dormitorio (living/comedor).
    -- Ej.: monoambiente = 1 amb / 0 dorm; "3 ambientes" = 2 dormitorios.
    CONSTRAINT ck_propiedad_dorm_vs_amb CHECK (cant_dormitorios < cant_ambientes),
    CONSTRAINT ck_propiedad_banios      CHECK (cant_banios >= 1),
    CONSTRAINT ck_propiedad_superficie  CHECK (superficie_total > 0),
    CONSTRAINT ck_propiedad_anio        CHECK (anio_construccion IS NULL OR anio_construccion >= 1800)
);

CREATE INDEX ix_propiedad_tipo      ON propiedad (tipo_propiedad);
CREATE INDEX ix_propiedad_localidad ON propiedad (lower(localidad));
CREATE INDEX ix_propiedad_ambientes ON propiedad (cant_ambientes);


-- ---------------------------------------------------------------------
-- PUBLICACION: una oferta concreta (venta o alquiler) de una propiedad
-- ---------------------------------------------------------------------
CREATE TABLE publicacion (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    propiedad_id            BIGINT        NOT NULL,
    titulo                  VARCHAR(120)  NOT NULL,
    descripcion             TEXT          NOT NULL,
    estado_publicacion      VARCHAR(20)   NOT NULL DEFAULT 'PAUSADA',
    tipo_operacion          VARCHAR(20)   NOT NULL,
    precio                  NUMERIC(14,2) NOT NULL,
    moneda                  VARCHAR(10)   NOT NULL,
    expensas                NUMERIC(12,2),               -- siempre en PESOS; NULL = no tiene
    estado_comercial        VARCHAR(20)   NOT NULL DEFAULT 'DISPONIBLE',
    fecha_creacion          TIMESTAMPTZ   NOT NULL DEFAULT now(),
    fecha_publicacion       TIMESTAMPTZ,                  -- primera vez que pasó a ACTIVA
    fecha_ult_actualizacion TIMESTAMPTZ   NOT NULL DEFAULT now(),

    CONSTRAINT fk_publicacion_propiedad
        FOREIGN KEY (propiedad_id) REFERENCES propiedad (id) ON DELETE RESTRICT,

    CONSTRAINT ck_publicacion_estado
        CHECK (estado_publicacion IN ('ACTIVA', 'PAUSADA', 'ELIMINADA')),
    CONSTRAINT ck_publicacion_operacion
        CHECK (tipo_operacion IN ('ALQUILER', 'VENTA')),
    CONSTRAINT ck_publicacion_moneda
        CHECK (moneda IN ('PESOS', 'DOLARES')),
    CONSTRAINT ck_publicacion_estado_comercial
        CHECK (estado_comercial IN ('DISPONIBLE', 'RESERVADA', 'ALQUILADA', 'VENDIDA')),
    CONSTRAINT ck_publicacion_precio   CHECK (precio > 0),
    CONSTRAINT ck_publicacion_expensas CHECK (expensas IS NULL OR expensas >= 0),

    -- Regla de negocio R3: el estado final tiene que coincidir con la operación.
    -- Una publicación de ALQUILER no puede quedar VENDIDA y viceversa.
    CONSTRAINT ck_publicacion_estado_vs_operacion CHECK (
        (estado_comercial <> 'ALQUILADA' OR tipo_operacion = 'ALQUILER') AND
        (estado_comercial <> 'VENDIDA'   OR tipo_operacion = 'VENTA')
    ),

    -- Si alguna vez estuvo activa, tiene fecha de publicación.
    CONSTRAINT ck_publicacion_fecha_publicacion CHECK (
        estado_publicacion <> 'ACTIVA' OR fecha_publicacion IS NOT NULL
    )
);

-- Regla de negocio R2: como máximo UNA publicación ACTIVA por propiedad
-- y por tipo de operación (evita avisos duplicados en el catálogo).
CREATE UNIQUE INDEX ux_publicacion_activa_por_operacion
    ON publicacion (propiedad_id, tipo_operacion)
    WHERE estado_publicacion = 'ACTIVA';

CREATE INDEX ix_publicacion_propiedad ON publicacion (propiedad_id);
-- Índice pensado para la consulta del catálogo público
CREATE INDEX ix_publicacion_catalogo
    ON publicacion (tipo_operacion, moneda, precio)
    WHERE estado_publicacion = 'ACTIVA';


-- ---------------------------------------------------------------------
-- IMAGEN_PROPIEDAD: galería de fotos del inmueble
-- ---------------------------------------------------------------------
CREATE TABLE imagen_propiedad (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    propiedad_id    BIGINT        NOT NULL,
    descripcion     VARCHAR(200),                 -- se usa como texto alternativo (alt)
    url             VARCHAR(500)  NOT NULL,       -- URL pública del storage externo
    storage_key     VARCHAR(255)  NOT NULL,       -- id del archivo en el storage (para borrarlo)
    orden           SMALLINT      NOT NULL,       -- 1 = portada
    fecha_creacion  TIMESTAMPTZ   NOT NULL DEFAULT now(),

    CONSTRAINT fk_imagen_propiedad
        FOREIGN KEY (propiedad_id) REFERENCES propiedad (id) ON DELETE RESTRICT,
    CONSTRAINT ck_imagen_orden CHECK (orden >= 1),
    CONSTRAINT ux_imagen_storage_key UNIQUE (storage_key),

    -- No puede haber dos fotos con el mismo orden en una propiedad.
    -- DEFERRABLE: permite reordenar (intercambiar 1 y 2) dentro de una
    -- transacción sin chocar con la restricción a mitad de camino.
    CONSTRAINT ux_imagen_orden_por_propiedad
        UNIQUE (propiedad_id, orden) DEFERRABLE INITIALLY DEFERRED
);


-- ---------------------------------------------------------------------
-- CONSULTA: mensaje de un interesado sobre una publicación
-- ---------------------------------------------------------------------
CREATE TABLE consulta (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    publicacion_id          BIGINT        NOT NULL,
    nombre                  VARCHAR(80)   NOT NULL,
    apellido                VARCHAR(80)   NOT NULL,
    email                   VARCHAR(120),
    telefono                VARCHAR(30),
    mensaje                 VARCHAR(2000) NOT NULL,
    estado                  VARCHAR(20)   NOT NULL DEFAULT 'NUEVA',
    fecha_creacion          TIMESTAMPTZ   NOT NULL DEFAULT now(),
    fecha_ult_actualizacion TIMESTAMPTZ   NOT NULL DEFAULT now(),

    CONSTRAINT fk_consulta_publicacion
        FOREIGN KEY (publicacion_id) REFERENCES publicacion (id) ON DELETE RESTRICT,
    CONSTRAINT ck_consulta_estado
        CHECK (estado IN ('NUEVA', 'CONTACTADA', 'EN_GESTION', 'CERRADA', 'DESCARTADA')),
    -- Sin al menos un medio de contacto, la consulta no sirve para nada.
    CONSTRAINT ck_consulta_contacto
        CHECK (email IS NOT NULL OR telefono IS NOT NULL),
    CONSTRAINT ck_consulta_mensaje CHECK (length(trim(mensaje)) > 0)
);

CREATE INDEX ix_consulta_publicacion ON consulta (publicacion_id);
-- Bandeja del panel: consultas por estado, las más nuevas primero
CREATE INDEX ix_consulta_bandeja ON consulta (estado, fecha_creacion DESC);


-- ---------------------------------------------------------------------
-- Comentarios (quedan dentro de la base, útiles al inspeccionarla)
-- ---------------------------------------------------------------------
COMMENT ON TABLE propiedad        IS 'Inmueble físico. Puede tener varias publicaciones (venta/alquiler) a lo largo del tiempo.';
COMMENT ON TABLE publicacion      IS 'Oferta concreta de una propiedad: operación, precio y estados.';
COMMENT ON TABLE imagen_propiedad IS 'Fotos del inmueble. El archivo vive en un storage externo; acá solo se guarda la referencia.';
COMMENT ON TABLE consulta         IS 'Mensaje de un interesado sobre una publicación. Nunca se borra (trazabilidad).';
COMMENT ON COLUMN publicacion.expensas IS 'Siempre expresadas en PESOS, sin importar la moneda del precio.';
COMMENT ON COLUMN propiedad.anio_construccion IS 'Se guarda el año y no la antigüedad: la antigüedad se calcula.';
